products = [
    {
      "_id" : "1",
      "name": "Airpods Wireless Bluetooth Headphones",
      "image": "/images/airpods.jpeg",
      "description": "Bluetooth technology lets you connect it with compatible devices wirelessly. High-quality AAC audio offers an immersive listening experience. Built-in microphone allows you to take calls while working.",
      "brand": "Apple",
      "category": "Electronics",
      "countInStock": 10,
      "price": 89.99,
      "rating": 4.5,
      "numReviews": 12,
    },
    {
      "_id" : "2",
      "name": "Samsung Galaxy Watch",
      "image": "/images/samsung_galaxy_watch.jpeg",
      "description": "Stay connected on the go with the Samsung Galaxy Watch. Track your workouts, receive notifications, and monitor your heart rate with this stylish and functional smartwatch.",
      "brand": "Samsung",
      "category": "Electronics",
      "countInStock": 5,
      "price": 249.99,
      "rating": 4,
      "numReviews": 8,
    },
    {
      "_id" : "3",
      "name": "Canon EOS Rebel T7 DSLR Camera",
      "image": "/images/canon_eos_rebel_t7.jpg",
      "description": "Capture stunning photos and videos with the Canon EOS Rebel T7 DSLR Camera. With its high-performance autofocus system and easy-to-use interface, it's perfect for both beginners and experienced photographers.",
      "brand": "Canon",
      "category": "Electronics",
      "countInStock": 3,
      "price": 499.99,
      "rating": 3.7,
      "numReviews": 10,
    },
    {
      "_id" : "4",
      "name": "Apple iPad Pro",
      "image": "/images/apple_ipad_pro.jpeg",
      "description": "Experience the power and versatility of the Apple iPad Pro. With its stunning Retina display, powerful A12Z Bionic chip, and support for the Apple Pencil and Smart Keyboard, it's the ultimate tool for creativity and productivity.",
      "brand": "Apple",
      "category": "Electronics",
      "countInStock": 0,
      "price": 799.99,
      "rating": 3.9,
      "numReviews": 15,
    },
    {
      "_id" : "5",
      "name": "Sony WH-1000XM4 Wireless Headphones",
      "image": "/images/sony_wh1000xm4.jpeg",
      "description": "Immerse yourself in music with the Sony WH-1000XM4 Wireless Headphones. Featuring industry-leading noise cancellation, Bluetooth connectivity, and up to 30 hours of battery life, they're perfect for music lovers on the go.",
      "brand": "Sony",
      "category": "Electronics",
      "countInStock": 6,
      "price": 349.99,
      "rating": 3.5,
      "numReviews": 20,
    },
    {
      "_id" : "6",
      "name": "DJI Mavic Air 2 Drone",
      "image": "/images/dji_mavic_air_2.jpeg",
      "description": "Capture breathtaking aerial footage with the DJI Mavic Air 2 Drone. With its advanced camera system, intelligent shooting modes, and up to 34 minutes of flight time, it's the perfect companion for your next adventure.",
      "brand": "DJI",
      "category": "Electronics",
      "countInStock": 4,
      "price": 799.99,
      "rating": 4,
      "numReviews": 18,
    },
    {
      "_id" : "7",
      "name": "Amazon Echo Dot (4th Gen)",
      "image": "/images/amazon_echo_dot.jpeg",
      "description": "Control your smart home and stream music with ease using the Amazon Echo Dot (4th Gen). With its compact design and powerful voice recognition, it's the perfect addition to any room.",
      "brand": "Amazon",
      "category": "Electronics",
      "countInStock": 12,
      "price": 49.99,
      "rating": 3.7,
      "numReviews": 25,
    },
    {
      "_id" : "8",
      "name": "GoPro HERO9 Black",
      "image": "/images/gopro_hero9_black.jpeg",
      "description": "Capture stunning 5K video and vibrant photos with the GoPro HERO9 Black. With its rugged design, advanced stabilization, and waterproof construction, it's the ultimate action camera for adventurers.",
      "brand": "GoPro",
      "category": "Electronics",
      "countInStock": 7,
      "price": 449.99,
      "rating": 3,
      "numReviews": 14,
    },
    {
      "_id" : "9",
      "name": "Microsoft Surface Laptop 4",
      "image": "/images/microsoft_surface_laptop_4.jpeg",
      "description": "Experience the perfect balance of performance and portability with the Microsoft Surface Laptop 4. With its sleek design, vibrant PixelSense display, and powerful performance, it's ideal for work and play.",
      "brand": "Microsoft",
      "category": "Electronics",
      "countInStock": 9,
      "price": 1299.99,
      "rating": 3.5,
      "numReviews": 22,
    },
    {
      "_id" : "10",
      "name": "Fitbit Versa 3 Smartwatch",
      "image": "/images/fitbit_versa_3.jpeg",
      "description": "Track your fitness goals and stay connected with the Fitbit Versa 3 Smartwatch. With its built-in GPS, heart rate monitor, and sleep tracking features, it's the perfect companion for an active lifestyle.",
      "brand": "Fitbit",
      "category": "Electronics",
      "countInStock": 15,
      "price": 229.99,
      "rating": 2.9,
      "numReviews": 30,
    }
  ]
